### ISSUE TITLE
cabal-docspec: doesn't run tests of internal modules

### ISSUE THREAD

**Issue by hasufell** [phadej/cabal-extras#143]
I went through the readme, but couldn't find a mention of this. Is this an inherent limitation or can it be fixed?

**Comment by phadej** [comment]
> Is this an inherent limitation 

Yes, it is.

When a precompiled package is loaded as a whole (not interpreted), non `exposed-modules`, i.e. `other-modules` cannot be loaded (with `:m +TheModule`).

I wish that at some point, `cabal-docspec` could use `:doc` and `:browse` to figure out exported symbols (and their docs), so otherwise exported things defined in hidden modules would be picked up (i.e. actually test the same you see in e.g. haddocks), but GHCi doesn't offer enough tools for such "unsupervised" use.
- https://gitlab.haskell.org/ghc/ghc/-/issues/24039
- also having a namespace specific `:doc-type` `:doc-term` commands to be unambiguous (currently `:doc` prints all matching symbols from all namespaces. This is not a blocking issue, but it is inconvenient)

Compare to the original Python doctest. It uses Python's reflection, i.e. doesn't read the source (and that's a good way to do it):

```
>>> import json
>>> json.__all__
['dump', 'dumps', 'load', 'loads', 'JSONDecoder', 'JSONEncoder']
>>> json.dump.__doc__
"Serialize ``obj`` as a JSON formatte...
```

and I wish GHCi had comparable inspection/reflection commands.
